/* $Id$ */
/* Copyright (c) 2007 The DeforaOS Project */



#ifndef LIBC_KERNEL_SOLARIS_SYS_UTSNAME_H
# define LIBC_KERNEL_SOLARIS_SYS_UTSNAME_H


/* struct utsname */
# define _UTSNAME_SIZE			257
# define _UTSNAME_SYSNAME_SIZE		_UTSNAME_SIZE
# define _UTSNAME_NODENAME_SIZE		_UTSNAME_SIZE
# define _UTSNAME_RELEASE_SIZE		_UTSNAME_SIZE
# define _UTSNAME_VERSION_SIZE		_UTSNAME_SIZE
# define _UTSNAME_MACHINE_SIZE		_UTSNAME_SIZE
# define _UTSNAME_PADDING_SIZE		_UTSNAME_SIZE

#endif /* !LIBC_KERNEL_SOLARIS_SYS_UTSNAME_H */
